"use client";
import {useCallback,useEffect,useState} from "react";
type Variant={id:string;platform:string;content:string};type Campaign={id:string;title:string;status:string;authenticity_passed:boolean;authenticity_score?:number;creative_direction?:string;video_direction?:string;source_evidence?:unknown[];content_variants?:Variant[]};
const label:Record<string,string>={linkedin:"LinkedIn",instagram:"Instagram",facebook:"Facebook",x:"X",tiktok:"TikTok / Reel",youtube:"YouTube Short"};
export default function ApprovalInbox(){
 const [campaigns,setCampaigns]=useState<Campaign[]>([]),[selected,setSelected]=useState<Campaign|null>(null),[tab,setTab]=useState("linkedin"),[note,setNote]=useState(""),[remember,setRemember]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/campaigns");const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not load campaigns");setCampaigns((x.campaigns||[]).filter((c:Campaign)=>["pending_approval","revision_requested"].includes(c.status)));},[]);
 useEffect(()=>{load().catch(e=>setMessage(e instanceof Error?e.message:"Could not load campaigns"));},[load]);
 const choose=(c:Campaign)=>{setSelected(c);setTab(c.content_variants?.[0]?.platform||"linkedin");setNote("");setRemember(false);setMessage("");};
 const revise=async()=>{if(!selected)return;setBusy(true);setMessage("");try{const r=await fetch("/api/campaigns/revise",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaignId:selected.id})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Revision failed");setSelected(null);setMessage("Revision completed and returned to CEO review.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Revision failed");}finally{setBusy(false);}};
 const decide=async(decision:string)=>{if(!selected)return;setBusy(true);setMessage("");try{const r=await fetch("/api/approvals",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({campaignId:selected.id,decision,feedback:note,rememberAsRule:remember})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Decision failed");setSelected(null);setNote("");setRemember(false);setMessage(x.learningWarning||("Campaign "+decision.replaceAll("_"," ")+". Publishing was not triggered."));await load();}catch(e){setMessage(e instanceof Error?e.message:"Decision failed");}finally{setBusy(false);}};
 const variants=selected?.content_variants||[],current=variants.find(v=>v.platform===tab);
 return <><header><div><p className="eyebrow">CEO APPROVAL</p><h1>Approval Inbox</h1><p>Inspect the complete campaign and its factual basis before anything moves to the calendar.</p></div></header>{message&&<div className="warningBox">{message}</div>}<div className="approvalLayout"><article className="panel approvalQueue"><h3>Waiting for you</h3>{campaigns.length?campaigns.map(c=><button className={selected?.id===c.id?"queueItem active":"queueItem"} key={c.id} onClick={()=>choose(c)}><b>{c.title}</b><small>{c.status.replaceAll("_"," ")} · {c.content_variants?.length||0} versions</small></button>):<div className="empty">Nothing is waiting for approval.</div>}</article><article className="panel">{!selected?<div className="empty">Select a campaign to review every platform version.</div>:<><div className="row"><div><span className="pill">{selected.status}</span><h2>{selected.title}</h2></div><span className={selected.authenticity_passed?"ready":"warning"}>{selected.authenticity_score??0}/100</span></div><div className="tabs">{variants.map(v=><button className={tab===v.platform?"active":""} key={v.id} onClick={()=>setTab(v.platform)}>{label[v.platform]||v.platform}</button>)}</div>{current&&<div className="approvalCopy"><b>{label[current.platform]||current.platform}</b><p>{current.content}</p></div>}<div className="directions"><div><b>Creative direction</b><p>{selected.creative_direction||"—"}</p></div><div><b>Video direction</b><p>{selected.video_direction||"—"}</p></div></div><div className="panel"><b>Source evidence</b>{selected.source_evidence?.length?<ul>{selected.source_evidence.map((e,i)=><li key={i}>{typeof e==="string"?e:JSON.stringify(e)}</li>)}</ul>:<p>No source evidence is attached.</p>}</div><label>CEO feedback</label><textarea rows={4} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain what should change."/><label className="check"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/> Remember this feedback as a Brand Brain rule</label><div className="actions">{selected.status==="revision_requested"&&<button className="primary" disabled={busy} onClick={()=>void revise()}>{busy?"Working…":"Regenerate from feedback"}</button>}<button className="primary" disabled={busy||!selected.authenticity_passed} onClick={()=>void decide("approved")}>Approve campaign</button><button disabled={busy||!note.trim()} onClick={()=>void decide("changes_requested")}>Request changes</button><button disabled={busy} onClick={()=>void decide("rejected")}>Reject</button></div></>}</article></div></>;
}