"use client";import {useCallback,useEffect,useState} from "react";
export default function BrandBrain(){
  const [data,setData]=useState<any>(null),[allEvidence,setAllEvidence]=useState<any[]>([]),[rule,setRule]=useState(""),[content,setContent]=useState(""),[kind,setKind]=useState("project"),[url,setUrl]=useState("");
  const load=useCallback(async()=>{const [brain,evidence]=await Promise.all([fetch("/api/brand-brain").then(r=>r.json()),fetch("/api/brand-brain/evidence").then(r=>r.json())]);setData(brain);setAllEvidence(evidence.evidence||[])},[]);
  useEffect(()=>{load().catch(()=>{})},[load]);
  const addRule=async()=>{if(!rule.trim())return;await fetch("/api/brand-brain/rules",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rule})});setRule("");load()};
  const addEvidence=async()=>{if(!content.trim())return;await fetch("/api/brand-brain/evidence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind,content,sourceUrl:url,approved:false})});setContent("");setUrl("");load()};
  const approve=async(id:string,approved:boolean)=>{await fetch("/api/brand-brain/evidence",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,approved})});load()};
  const pending=allEvidence.filter(x=>!x.approved),approved=allEvidence.filter(x=>x.approved);
  return <><header><div><p className="eyebrow">PERSISTENT MARKETING MEMORY</p><h1>Elyrac Brand Brain</h1><p>Teach the system what is true about Elyrac, how the brand should behave, and which evidence it may use.</p></div></header><div className="grid"><article className="panel"><h3>Core positioning</h3><p className="lead">{data?.core?.positioning||"Loading…"}</p><h3>Add CEO rule</h3><textarea rows={3} value={rule} onChange={e=>setRule(e.target.value)} placeholder="Example: Never use more than one logo in a visual."/><button className="primary" onClick={addRule}>Add rule</button><h3>Active learned rules</h3>{data?.rules?.map((r:any)=><div className="rule" key={r.id}><span>{r.rule}</span><small>{r.source}</small></div>)}</article><article className="panel"><span className="pill">EVIDENCE LIBRARY</span><h3>Add real Elyrac evidence</h3><select value={kind} onChange={e=>setKind(e.target.value)}><option value="project">Project</option><option value="case_study">Case study</option><option value="founder_pov">Founder POV</option><option value="website">Website</option><option value="product">Product</option><option value="client_question">Client question</option><option value="company_update">Company update</option><option value="approved_copy">Approved copy</option></select><textarea rows={5} value={content} onChange={e=>setContent(e.target.value)} placeholder="What happened, what was learned, or what Elyrac believes…"/><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Optional source URL"/><button className="primary" onClick={addEvidence}>Save for review</button><h3>Awaiting approval</h3>{pending.length?pending.map((x:any)=><div className="rule" key={x.id}><div><b>{x.kind}</b><p>{x.content}</p></div><button onClick={()=>approve(x.id,true)}>Approve evidence</button></div>):<p>No evidence awaiting approval.</p>}<h3>Approved evidence</h3>{approved.length?approved.map((x:any)=><div className="rule" key={x.id}><div><b>{x.kind}</b><p>{x.content}</p></div><button onClick={()=>approve(x.id,false)}>Remove approval</button></div>):<p>No approved evidence yet.</p>}</article></div></>
}