"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
type CalendarItem={id:string;title:string;objective?:string|null;pillar?:string|null;status:string;scheduled_at?:string|null};
export default function ContentCalendar(){
 const [items,setItems]=useState<CalendarItem[]>([]),[times,setTimes]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>(null),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch("/api/calendar");const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not load calendar");setItems(x.items||[]);}catch(e){setMessage(e instanceof Error?e.message:"Could not load calendar");}},[]);
 useEffect(()=>{void load();},[load]);
 const approved=useMemo(()=>items.filter(x=>x.status==="approved"),[items]),scheduled=useMemo(()=>items.filter(x=>x.status==="scheduled"),[items]);
 async function schedule(campaignId:string){const local=times[campaignId];if(!local){setMessage("Choose a date and time first.");return;}setBusy(campaignId);setMessage("");try{const r=await fetch("/api/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({campaignId,scheduledAt:new Date(local).toISOString()})});const x=await r.json();if(!r.ok)throw new Error(x.error||"Could not schedule campaign");setMessage("Campaign scheduled successfully. Nothing was published.");await load();}catch(e){setMessage(e instanceof Error?e.message:"Could not schedule campaign");}finally{setBusy(null);}}
 const Card=({c}:{c:CalendarItem})=><article className="panel" key={c.id}><div className="row"><span className="pill">{c.status.replaceAll("_"," ")}</span>{c.scheduled_at&&<small>{new Date(c.scheduled_at).toLocaleDateString()}</small>}</div><h3>{c.title}</h3>{c.objective&&<p>{c.objective}</p>}{c.pillar&&<small>{c.pillar}</small>}{c.status==="scheduled"?<p><b>Scheduled:</b> {new Date(c.scheduled_at!).toLocaleString()}</p>:<div className="schedule"><input aria-label={"Schedule "+c.title} type="datetime-local" min={new Date(Date.now()+60000).toISOString().slice(0,16)} value={times[c.id]||""} onChange={e=>setTimes(v=>({...v,[c.id]:e.target.value}))}/><button className="primary" onClick={()=>void schedule(c.id)} disabled={busy===c.id}>{busy===c.id?"Scheduling…":"Schedule campaign"}</button></div>}</article>;
 return <><header><div><p className="eyebrow">CONTENT OPERATIONS</p><h1>Content Calendar</h1><p>Move CEO-approved campaigns into the publishing plan. Scheduling does not publish content.</p></div></header>
 {message&&<div className="warningBox">{message}</div>}
 <div className="stats"><article className="stat"><span>Ready to schedule</span><strong>{approved.length}</strong></article><article className="stat"><span>Scheduled</span><strong>{scheduled.length}</strong></article><article className="stat"><span>Total planned</span><strong>{items.length}</strong></article></div>
 <section><div className="row"><div><p className="eyebrow">APPROVED</p><h2>Ready to schedule</h2></div></div><div className="calendar">{approved.length?approved.map(c=><Card key={c.id} c={c}/>):<div className="empty">No approved campaigns are waiting for a date. Approve one in the Approval Inbox first.</div>}</div></section>
 <section><div className="row"><div><p className="eyebrow">UPCOMING</p><h2>Scheduled campaigns</h2></div></div><div className="calendar">{scheduled.length?scheduled.map(c=><Card key={c.id} c={c}/>):<div className="empty">Nothing is scheduled yet.</div>}</div></section></>;
}