"use client";import {useEffect,useState} from "react";import CampaignReview from "./CampaignReview";
const KEY="elyrac-content-studio-draft-v1";
export default function ContentStudio({seed,onSeedConsumed}:{seed?:any;onSeedConsumed?:()=>void}){
 const [evidence,setEvidence]=useState(""),[focus,setFocus]=useState(""),[result,setResult]=useState<any>(null),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[restored,setRestored]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const x=JSON.parse(raw);setEvidence(x.evidence||"");setFocus(x.focus||"");setResult(x.result||null);setSaved(Boolean(x.saved))}}catch{}finally{setRestored(true)}},[]);
 useEffect(()=>{if(!restored)return;try{localStorage.setItem(KEY,JSON.stringify({evidence,focus,result,saved}))}catch{}},[evidence,focus,result,saved,restored]);
 useEffect(()=>{if(seed){setEvidence([`Headline: ${seed.headline}`,`Publisher: ${seed.source_name}`,`Published: ${seed.published_at}`,`Source: ${seed.source_url}`,`Verified summary: ${seed.summary}`].join("\n"));setFocus(`Develop Elyrac's original perspective from this verified trend. Starting angle: ${seed.elyrac_angle}. Business implication: ${seed.business_implication}. Do not merely rewrite the headline.`);onSeedConsumed?.()}},[seed,onSeedConsumed]);
 const generate=async()=>{setBusy(true);setSaved(false);setResult(null);try{const r=await fetch("/api/campaigns/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({evidence:evidence.split("\n").map(x=>x.trim()).filter(Boolean),focus})});setResult(await r.json())}finally{setBusy(false)}};
 const clear=()=>{setEvidence("");setFocus("");setResult(null);setSaved(false);try{localStorage.removeItem(KEY)}catch{}};
 return <><header><div><p className="eyebrow">CONTENT STUDIO</p><h1>Create from something real.</h1><p>Start with approved Elyrac evidence or a verified global signal. The strategist must add a distinct Elyrac point of view.</p></div>{(evidence||focus||result)&&<button onClick={clear}>Clear draft</button>}</header><article className="panel"><label>Evidence / source material</label><textarea rows={8} value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="One fact, observation or verified source per line"/><label>Strategic focus</label><textarea rows={4} value={focus} onChange={e=>setFocus(e.target.value)} placeholder="Founder POV, brand authority, product education"/><button className="primary" disabled={busy||!evidence.trim()} onClick={generate}>{busy?"Strategist is working…":"Generate Elyrac campaign"}</button>{restored&&(evidence||focus||result)&&<small> Draft autosaved in this browser.</small>}</article>{result?.error&&<article className="panel warningBox">{result.error}</article>}{result?.draft&&<CampaignReview result={result} onSaved={()=>setSaved(true)}/>} {saved&&<div className="successBox">Campaign saved. It is now available to the CEO approval workflow.</div>}</>}