import type {SocialPlatform} from "./oauth";
export type ProviderIdentity={externalAccountId:string;accountLabel:string};
async function json(url:string,token:string){const r=await fetch(url,{headers:{authorization:`Bearer ${token}`,accept:"application/json"},cache:"no-store"});if(!r.ok)throw new Error(`Provider identity verification failed (${r.status})`);return await r.json() as Record<string,unknown>}
export async function verifyProviderIdentity(platform:SocialPlatform,token:string):Promise<ProviderIdentity>{
 if(platform==="facebook"||platform==="instagram"){const d=await json("https://graph.facebook.com/v21.0/me?fields=id,name",token);if(typeof d.id!=="string")throw new Error("Provider returned no account identity");return {externalAccountId:d.id,accountLabel:typeof d.name==="string"?d.name:d.id}}
 if(platform==="linkedin"){const d=await json("https://api.linkedin.com/v2/userinfo",token);if(typeof d.sub!=="string")throw new Error("Provider returned no account identity");return {externalAccountId:d.sub,accountLabel:typeof d.name==="string"?d.name:d.sub}}
 if(platform==="x"){const d=await json("https://api.x.com/2/users/me?user.fields=name,username",token);const u=d.data as Record<string,unknown>|undefined;if(!u||typeof u.id!=="string")throw new Error("Provider returned no account identity");return {externalAccountId:u.id,accountLabel:typeof u.username==="string"?`@${u.username}`:typeof u.name==="string"?u.name:u.id}}
 if(platform==="tiktok"){const d=await json("https://open.tiktokapis.com/v2/user/info/?fields=open_id,display_name",token);const wrap=d.data as Record<string,unknown>|undefined,u=wrap?.user as Record<string,unknown>|undefined;if(!u||typeof u.open_id!=="string")throw new Error("Provider returned no account identity");return {externalAccountId:u.open_id,accountLabel:typeof u.display_name==="string"?u.display_name:u.open_id}}
 const d=await json("https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true",token),items=d.items as Array<Record<string,unknown>>|undefined,u=items?.[0];if(!u||typeof u.id!=="string")throw new Error("No YouTube channel found for authorized account");const s=u.snippet as Record<string,unknown>|undefined;return {externalAccountId:u.id,accountLabel:typeof s?.title==="string"?s.title:u.id}
}
